In [1]:
import numpy as np

In [4]:
A = np.array([[1,2,3,4,5,6,7],
              [1.5, 3.8, 6.7, 9.0, 11.2, 13.6, 16]])

In [3]:
x = np.array([1,2,3,4,5,6,7])
np.column_stack((np.ones(len(x)), x))

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.],
       [1., 7.]])

In [4]:
np.size(x)

7

In [19]:


def qr_decomposition(A):
    # Extraindo dimenssões da matriz A
    m, n = A.shape
    
    
    # Definição de matriz com zeros de dimenssões adequadas       
    Q = np.zeros((m, n)) # Q será uma matriz de tamanho [m] e [n]
    R = np.zeros((n, n)) # R será uma matriz quadrada
    
    
    # Para j na faixa de n:
    for j in range(n): 
        
        # Variável v = todas as linhas de A e coluna j, sendo [v] 
        #   matrizes compostas por (x_i,  y_i)
        v = A[:, j]
        
        # Para i na faixa de j:
        for i in range(j):
            
            # Matriz R de linha i e coluna j = produto escalar de todas as linha de Q
            #   de coluna i, estando i na faixa de 0-j com todas as linhas de A e coluna
            #   j, estando j na faixa de 0-n.
            
            # Matriz [R] (triangular superior) será será definida pelo produto escalar da
            #   matriz [Q] com matriz v, sendo que suas posições são definidas por i e j.
            R[i, j] = np.dot(Q[:, i], v) 
            
            # matriz v, comporta por x_i e y_i definida por matriz v subtraído matriz
            #   [R] (triangular superior) de índices (i, j) multiplicado por todas as linhas
            #    da coluna i da matriz ortogonal [Q]               
            v = v - R[i, j] * Q[:, i]
            
        # Matriz [R](j,j) é igual a norma de Frobenius do vetor v (todas as linhas de A e coluna j)
        # (...)
        # Dado um matriz A = (1,2) e B = (3, 4), a norma de Frobenius vai ser: ⎷(1² + 2² + 3² + 4²).
        # Por definição, a norma é definida pela raiz quadrada da soma dos elementos das matrizes elevados ao quadrado.
        R[j, j] = np.linalg.norm(v)
        
        # As linhas da coluna j da matriz ortogonal [Q] será dado pelo vetor v | v = v - R[i, j] * Q[:, i]
        #   dividido pelo vetor triangular superior [R] (j, j).
        Q[:, j] = v / R[j, j]
        
    # Retorna matriz ortogonal Q e matriz triangular superior R.
    return Q, R

qr_decomposition(A)

/var/folders/tf/5c5cm4z11mvb4z72rkp1jvxw0000gn/T/ipykernel_57204/3555969516.py:41: RuntimeWarning: invalid value encountered in divide
  Q[:, j] = v / R[j, j]


(array([[ 0.5547002 , -0.83205029,  0.        , -1.        ,         nan,
                 nan,         nan],
        [ 0.83205029,  0.5547002 ,  1.        ,  0.        ,         nan,
                 nan,         nan]]),
 array([[ 1.80277564e+00,  4.27119151e+00,  7.23883756e+00,
          9.70725343e+00,  1.20924643e+01,  1.46440852e+01,
          1.71957061e+01],
        [ 0.00000000e+00,  4.43760157e-01,  1.22034043e+00,
          1.66410059e+00,  2.05239073e+00,  2.55162090e+00,
          3.05085108e+00],
        [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
         -1.22124533e-15, -4.44089210e-16,  4.44089210e-16,
         -2.22044605e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.11022302e-15,  4.44089210e-16,  0.00000000e+00,
          8.88178420e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,             nan,
                     nan],
        [ 0.00000000e+00,  0.00000000e+00, 